[project]
name = "sar-review-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "carlosvts", email = "carlosvtsdev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
sar-review-pipeline = "sar_review_pipeline:main"
step01-fetch = "sar_review_pipeline.fetch_metadata.__main__:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
